/**
 * Curated seed catalogue: ~5 dishes per cuisine across all 10 categories.
 *
 * Images are real, high-quality food photos hosted on Unsplash (we store the URL
 * only — no binary uploads — per the project spec). The `&w=800&q=80&fit=crop`
 * params keep payloads small and the aspect ratio consistent in the grid.
 *
 * If an individual image ever 404s, the frontend renders a branded fallback,
 * so the catalogue degrades gracefully.
 */

const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;

export const dishesData = [
  /* ----------------------------- African ----------------------------- */
  {
    name: 'Jollof Rice with Grilled Chicken',
    cuisine: 'African',
    description:
      'Smoky West-African party jollof — long-grain rice simmered in a rich tomato-pepper base, served with charcoal-grilled chicken and fried plantain.',
    price: 13.5,
    image: img('1604908176997-125f25cc6f3d'),
    rating: 4.8,
    isVeg: false,
    prepTime: 30,
    tags: ['spicy', 'rice', 'grilled', 'popular'],
    ingredients: ['Long-grain rice', 'Tomato', 'Scotch bonnet', 'Chicken', 'Plantain'],
    addOns: [
      { name: 'Extra plantain', price: 2 },
      { name: 'Moin moin', price: 3 },
    ],
  },
  {
    name: 'Bunny Chow',
    cuisine: 'African',
    description:
      'A South-African street classic: a hollowed loaf of bread filled with fragrant, slow-cooked lamb curry.',
    price: 11.0,
    image: img('1606755962773-d324e0a13086'),
    rating: 4.5,
    isVeg: false,
    prepTime: 35,
    tags: ['curry', 'street food', 'lamb'],
    ingredients: ['White bread', 'Lamb', 'Curry spices', 'Onion', 'Tomato'],
  },
  {
    name: 'Injera with Doro Wat',
    cuisine: 'African',
    description:
      'Ethiopian sourdough flatbread paired with doro wat, a deeply spiced chicken stew with berbere and a soft-boiled egg.',
    price: 14.0,
    image: img('1567364816519-cbc9c4ffe1eb'),
    rating: 4.7,
    isVeg: false,
    prepTime: 40,
    tags: ['stew', 'spicy', 'traditional'],
    ingredients: ['Teff flour', 'Chicken', 'Berbere', 'Egg', 'Niter kibbeh'],
  },
  {
    name: 'Vegetable Tagine',
    cuisine: 'African',
    description:
      'Slow-braised North-African vegetable stew with apricots, chickpeas and warm spices, served over couscous.',
    price: 10.5,
    image: img('1547592180-85f173990554'),
    rating: 4.4,
    isVeg: true,
    prepTime: 45,
    tags: ['vegan', 'stew', 'couscous', 'healthy'],
    ingredients: ['Chickpeas', 'Apricot', 'Carrot', 'Couscous', 'Ras el hanout'],
  },
  {
    name: 'Suya Beef Skewers',
    cuisine: 'African',
    description:
      'Nigerian street-grilled beef skewers coated in a nutty, peppery yaji spice rub. Served with sliced onions and tomato.',
    price: 9.5,
    image: img('1529193591184-b1d58069ecdd'),
    rating: 4.6,
    isVeg: false,
    prepTime: 20,
    tags: ['grilled', 'spicy', 'street food', 'skewers'],
    ingredients: ['Beef', 'Peanut', 'Cayenne', 'Onion', 'Ginger'],
  },

  /* ----------------------------- Italian ----------------------------- */
  {
    name: 'Margherita Pizza',
    cuisine: 'Italian',
    description:
      'Naples-style wood-fired pizza with San Marzano tomato, fior di latte mozzarella, fresh basil and a drizzle of olive oil.',
    price: 12.0,
    image: img('1604382354936-07c5d9983bd3'),
    rating: 4.9,
    isVeg: true,
    prepTime: 18,
    tags: ['pizza', 'cheese', 'classic', 'popular'],
    ingredients: ['Tomato', 'Mozzarella', 'Basil', 'Olive oil', '00 flour'],
    addOns: [
      { name: 'Extra mozzarella', price: 2.5 },
      { name: 'Truffle oil', price: 3 },
    ],
  },
  {
    name: 'Spaghetti Carbonara',
    cuisine: 'Italian',
    description:
      'Roman carbonara done right — guanciale, pecorino romano, egg yolk and cracked black pepper. No cream.',
    price: 13.5,
    image: img('1612874742237-6526221588e3'),
    rating: 4.7,
    isVeg: false,
    prepTime: 20,
    tags: ['pasta', 'creamy', 'classic'],
    ingredients: ['Spaghetti', 'Guanciale', 'Pecorino', 'Egg yolk', 'Black pepper'],
  },
  {
    name: 'Margherita Lasagna',
    cuisine: 'Italian',
    description:
      'Layers of fresh pasta, slow-cooked beef ragu, béchamel and parmesan baked until golden and bubbling.',
    price: 14.0,
    image: img('1574894709920-11b28e7367e3'),
    rating: 4.6,
    isVeg: false,
    prepTime: 35,
    tags: ['pasta', 'baked', 'cheese'],
    ingredients: ['Pasta sheets', 'Beef ragu', 'Béchamel', 'Parmesan', 'Tomato'],
  },
  {
    name: 'Risotto ai Funghi',
    cuisine: 'Italian',
    description:
      'Creamy Carnaroli rice slow-stirred with porcini and button mushrooms, white wine and parmesan.',
    price: 13.0,
    image: img('1476124369491-e7addf5db371'),
    rating: 4.5,
    isVeg: true,
    prepTime: 30,
    tags: ['risotto', 'mushroom', 'creamy'],
    ingredients: ['Carnaroli rice', 'Porcini', 'White wine', 'Parmesan', 'Butter'],
  },
  {
    name: 'Tiramisu',
    cuisine: 'Italian',
    description:
      'Classic no-bake dessert of espresso-soaked savoiardi layered with mascarpone cream and dusted cocoa.',
    price: 7.5,
    image: img('1571877227200-a0d98ea607e9'),
    rating: 4.8,
    isVeg: true,
    prepTime: 10,
    tags: ['dessert', 'coffee', 'sweet'],
    ingredients: ['Mascarpone', 'Espresso', 'Savoiardi', 'Cocoa', 'Egg'],
  },

  /* ----------------------------- Indian ----------------------------- */
  {
    name: 'Butter Chicken',
    cuisine: 'Indian',
    description:
      'Tandoor-charred chicken simmered in a velvety tomato-butter gravy with fenugreek and cream. Best with naan.',
    price: 13.0,
    image: img('1588166524941-3bf61a9c41db'),
    rating: 4.9,
    isVeg: false,
    prepTime: 30,
    tags: ['curry', 'creamy', 'popular', 'mild'],
    ingredients: ['Chicken', 'Tomato', 'Butter', 'Cream', 'Kasuri methi'],
    addOns: [
      { name: 'Butter naan', price: 2 },
      { name: 'Jeera rice', price: 3 },
    ],
  },
  {
    name: 'Paneer Tikka Masala',
    cuisine: 'Indian',
    description:
      'Char-grilled cottage cheese cubes in a spiced onion-tomato masala with bell peppers.',
    price: 12.0,
    image: img('1631452180519-c014fe946bc7'),
    rating: 4.7,
    isVeg: true,
    prepTime: 28,
    tags: ['curry', 'paneer', 'vegetarian'],
    ingredients: ['Paneer', 'Bell pepper', 'Onion', 'Tomato', 'Garam masala'],
  },
  {
    name: 'Hyderabadi Chicken Biryani',
    cuisine: 'Indian',
    description:
      'Fragrant basmati layered with marinated chicken, saffron and fried onions, dum-cooked and served with raita.',
    price: 14.5,
    image: img('1563379091339-03b21ab4a4f8'),
    rating: 4.8,
    isVeg: false,
    prepTime: 40,
    tags: ['biryani', 'rice', 'spicy', 'popular'],
    ingredients: ['Basmati rice', 'Chicken', 'Saffron', 'Yogurt', 'Whole spices'],
  },
  {
    name: 'Masala Dosa',
    cuisine: 'Indian',
    description:
      'Crispy fermented rice-lentil crepe wrapped around spiced potato, with sambar and coconut chutney.',
    price: 9.0,
    image: img('1668236543090-82eba5ee5976'),
    rating: 4.6,
    isVeg: true,
    prepTime: 20,
    tags: ['south indian', 'breakfast', 'vegan'],
    ingredients: ['Rice', 'Urad dal', 'Potato', 'Sambar', 'Coconut chutney'],
  },
  {
    name: 'Chole Bhature',
    cuisine: 'Indian',
    description:
      'Punjabi spiced chickpea curry served with fluffy deep-fried bhature and pickled onions.',
    price: 10.0,
    image: img('1626500155537-89e84d5b4bf2'),
    rating: 4.5,
    isVeg: true,
    prepTime: 25,
    tags: ['curry', 'street food', 'vegetarian'],
    ingredients: ['Chickpeas', 'Flour', 'Onion', 'Tomato', 'Chana masala'],
  },

  /* ----------------------------- Chinese ----------------------------- */
  {
    name: 'Kung Pao Chicken',
    cuisine: 'Chinese',
    description:
      'Sichuan stir-fry of diced chicken, peanuts and dried chillies in a tangy-sweet sauce with a numbing kick.',
    price: 12.5,
    image: img('1525755662778-989d0524087e'),
    rating: 4.6,
    isVeg: false,
    prepTime: 20,
    tags: ['stir fry', 'spicy', 'sichuan'],
    ingredients: ['Chicken', 'Peanut', 'Dried chilli', 'Sichuan pepper', 'Soy'],
  },
  {
    name: 'Vegetable Hakka Noodles',
    cuisine: 'Chinese',
    description:
      'Wok-tossed noodles with julienned vegetables, garlic and a glossy soy-chilli sauce.',
    price: 9.5,
    image: img('1585032226651-759b368d7246'),
    rating: 4.4,
    isVeg: true,
    prepTime: 18,
    tags: ['noodles', 'stir fry', 'vegetarian'],
    ingredients: ['Noodles', 'Cabbage', 'Carrot', 'Bell pepper', 'Soy'],
  },
  {
    name: 'Pork Dumplings',
    cuisine: 'Chinese',
    description:
      'Steamed handmade dumplings stuffed with seasoned pork and chives, served with black-vinegar dip.',
    price: 10.5,
    image: img('1563245372-f21724e3856d'),
    rating: 4.7,
    isVeg: false,
    prepTime: 22,
    tags: ['dumplings', 'steamed', 'dim sum'],
    ingredients: ['Pork', 'Chives', 'Ginger', 'Dumpling wrapper', 'Black vinegar'],
  },
  {
    name: 'Sweet & Sour Chicken',
    cuisine: 'Chinese',
    description:
      'Crispy battered chicken tossed with pineapple, peppers and onion in a glossy sweet-sour glaze.',
    price: 11.5,
    image: img('1603073163308-9654c3fb70b5'),
    rating: 4.3,
    isVeg: false,
    prepTime: 24,
    tags: ['fried', 'sweet', 'classic'],
    ingredients: ['Chicken', 'Pineapple', 'Bell pepper', 'Vinegar', 'Sugar'],
  },
  {
    name: 'Mapo Tofu',
    cuisine: 'Chinese',
    description:
      'Silken tofu braised in a fiery, savoury doubanjiang-and-chilli-oil sauce with minced pork.',
    price: 10.0,
    image: img('1582032215298-b4c2c7e9e4d4'),
    rating: 4.5,
    isVeg: false,
    prepTime: 20,
    tags: ['tofu', 'spicy', 'sichuan'],
    ingredients: ['Silken tofu', 'Pork', 'Doubanjiang', 'Chilli oil', 'Scallion'],
  },

  /* ----------------------------- Mexican ----------------------------- */
  {
    name: 'Chicken Tacos al Pastor',
    cuisine: 'Mexican',
    description:
      'Soft corn tortillas with marinated spit-grilled chicken, pineapple, onion and cilantro.',
    price: 10.5,
    image: img('1565299624946-b28f40a0ae38'),
    rating: 4.7,
    isVeg: false,
    prepTime: 18,
    tags: ['tacos', 'street food', 'popular'],
    ingredients: ['Corn tortilla', 'Chicken', 'Pineapple', 'Onion', 'Cilantro'],
    addOns: [
      { name: 'Guacamole', price: 2 },
      { name: 'Extra salsa', price: 1 },
    ],
  },
  {
    name: 'Beef Burrito',
    cuisine: 'Mexican',
    description:
      'Flour tortilla loaded with seasoned beef, rice, black beans, cheese, salsa and sour cream.',
    price: 11.5,
    image: img('1626700051175-6818013e1d4f'),
    rating: 4.5,
    isVeg: false,
    prepTime: 16,
    tags: ['burrito', 'hearty', 'wrap'],
    ingredients: ['Tortilla', 'Beef', 'Rice', 'Black beans', 'Cheese'],
  },
  {
    name: 'Loaded Nachos',
    cuisine: 'Mexican',
    description:
      'Crispy tortilla chips smothered in melted cheese, jalapeños, pico de gallo and guacamole.',
    price: 9.0,
    image: img('1513456852971-30c0b8199d4d'),
    rating: 4.4,
    isVeg: true,
    prepTime: 14,
    tags: ['snack', 'cheese', 'sharing'],
    ingredients: ['Tortilla chips', 'Cheese', 'Jalapeño', 'Tomato', 'Avocado'],
  },
  {
    name: 'Veggie Quesadilla',
    cuisine: 'Mexican',
    description:
      'Grilled flour tortilla folded over melted cheese, peppers, corn and black beans.',
    price: 9.5,
    image: img('1618040996337-56904b7850b9'),
    rating: 4.3,
    isVeg: true,
    prepTime: 15,
    tags: ['cheese', 'grilled', 'vegetarian'],
    ingredients: ['Tortilla', 'Cheese', 'Bell pepper', 'Corn', 'Black beans'],
  },
  {
    name: 'Carne Asada Bowl',
    cuisine: 'Mexican',
    description:
      'Citrus-marinated grilled steak over cilantro-lime rice with beans, salsa verde and avocado.',
    price: 12.5,
    image: img('1543339308-43e59d6b73a6'),
    rating: 4.6,
    isVeg: false,
    prepTime: 22,
    tags: ['bowl', 'grilled', 'healthy'],
    ingredients: ['Steak', 'Rice', 'Beans', 'Salsa verde', 'Avocado'],
  },

  /* --------------------------- Continental --------------------------- */
  {
    name: 'Grilled Salmon with Asparagus',
    cuisine: 'Continental',
    description:
      'Pan-seared salmon fillet with a lemon-butter glaze, served with charred asparagus and baby potatoes.',
    price: 17.0,
    image: img('1467003909585-2f8a72700288'),
    rating: 4.8,
    isVeg: false,
    prepTime: 25,
    tags: ['seafood', 'healthy', 'grilled', 'premium'],
    ingredients: ['Salmon', 'Asparagus', 'Lemon', 'Butter', 'Potato'],
  },
  {
    name: 'Herb-Roast Chicken',
    cuisine: 'Continental',
    description:
      'Half chicken roasted with rosemary and thyme, served with seasonal vegetables and pan jus.',
    price: 15.0,
    image: img('1598103442097-8b74394b95c6'),
    rating: 4.6,
    isVeg: false,
    prepTime: 35,
    tags: ['roast', 'comfort', 'hearty'],
    ingredients: ['Chicken', 'Rosemary', 'Thyme', 'Vegetables', 'Garlic'],
  },
  {
    name: 'Caesar Salad',
    cuisine: 'Continental',
    description:
      'Crisp romaine tossed in creamy Caesar dressing with parmesan shavings and garlic croutons.',
    price: 8.5,
    image: img('1550304943-4f24f54ddde9'),
    rating: 4.3,
    isVeg: true,
    prepTime: 10,
    tags: ['salad', 'healthy', 'light'],
    ingredients: ['Romaine', 'Parmesan', 'Croutons', 'Caesar dressing', 'Lemon'],
  },
  {
    name: 'Mushroom Soup',
    cuisine: 'Continental',
    description:
      'Velvety cream of mushroom soup finished with truffle oil and served with toasted bread.',
    price: 7.0,
    image: img('1547592166-23ac45744acd'),
    rating: 4.4,
    isVeg: true,
    prepTime: 18,
    tags: ['soup', 'creamy', 'starter'],
    ingredients: ['Mushroom', 'Cream', 'Onion', 'Truffle oil', 'Bread'],
  },
  {
    name: 'Beef Steak with Mash',
    cuisine: 'Continental',
    description:
      'Char-grilled sirloin cooked to your liking, served with buttery mash and peppercorn sauce.',
    price: 19.0,
    image: img('1600891964092-4316c288032e'),
    rating: 4.7,
    isVeg: false,
    prepTime: 30,
    tags: ['steak', 'premium', 'hearty'],
    ingredients: ['Sirloin', 'Potato', 'Butter', 'Peppercorn', 'Cream'],
  },

  /* ------------------------------ Thai ------------------------------ */
  {
    name: 'Pad Thai',
    cuisine: 'Thai',
    description:
      'Stir-fried rice noodles with prawns, egg, tofu, bean sprouts and crushed peanuts in tamarind sauce.',
    price: 12.0,
    image: img('1559314809-0d155014e29e'),
    rating: 4.7,
    isVeg: false,
    prepTime: 20,
    tags: ['noodles', 'stir fry', 'popular'],
    ingredients: ['Rice noodles', 'Prawn', 'Egg', 'Tamarind', 'Peanut'],
  },
  {
    name: 'Green Curry with Chicken',
    cuisine: 'Thai',
    description:
      'Aromatic coconut green curry with chicken, Thai basil, bamboo shoots and kaffir lime.',
    price: 12.5,
    image: img('1455619452474-d2be8b1e70cd'),
    rating: 4.6,
    isVeg: false,
    prepTime: 24,
    tags: ['curry', 'coconut', 'spicy'],
    ingredients: ['Chicken', 'Green curry paste', 'Coconut milk', 'Thai basil', 'Bamboo'],
  },
  {
    name: 'Tom Yum Soup',
    cuisine: 'Thai',
    description:
      'Hot-and-sour prawn soup with lemongrass, galangal, lime leaves, chilli and mushrooms.',
    price: 9.5,
    image: img('1569562211093-4ed0d0758f12'),
    rating: 4.5,
    isVeg: false,
    prepTime: 18,
    tags: ['soup', 'spicy', 'sour'],
    ingredients: ['Prawn', 'Lemongrass', 'Galangal', 'Lime leaf', 'Mushroom'],
  },
  {
    name: 'Mango Sticky Rice',
    cuisine: 'Thai',
    description:
      'Sweet coconut sticky rice with fresh ripe mango and a drizzle of salted coconut cream.',
    price: 7.0,
    image: img('1711161629377-3b3b6e3a8a3a'),
    rating: 4.8,
    isVeg: true,
    prepTime: 12,
    tags: ['dessert', 'sweet', 'coconut'],
    ingredients: ['Glutinous rice', 'Mango', 'Coconut milk', 'Sugar', 'Salt'],
  },
  {
    name: 'Thai Basil Fried Rice',
    cuisine: 'Thai',
    description:
      'Wok-fired jasmine rice with holy basil, chilli, garlic and your choice of protein, topped with a fried egg.',
    price: 10.5,
    image: img('1512058564366-18510be2db19'),
    rating: 4.4,
    isVeg: true,
    prepTime: 16,
    tags: ['rice', 'stir fry', 'spicy'],
    ingredients: ['Jasmine rice', 'Holy basil', 'Chilli', 'Garlic', 'Egg'],
  },

  /* ----------------------------- Japanese ----------------------------- */
  {
    name: 'Salmon Avocado Sushi Roll',
    cuisine: 'Japanese',
    description:
      'Fresh salmon and avocado rolled in seasoned sushi rice and nori, served with soy, wasabi and ginger.',
    price: 13.5,
    image: img('1579871494447-9811cf80d66c'),
    rating: 4.8,
    isVeg: false,
    prepTime: 22,
    tags: ['sushi', 'seafood', 'popular'],
    ingredients: ['Sushi rice', 'Salmon', 'Avocado', 'Nori', 'Soy'],
  },
  {
    name: 'Tonkotsu Ramen',
    cuisine: 'Japanese',
    description:
      'Rich pork-bone broth with springy noodles, chashu, soft egg, scallions and nori.',
    price: 14.0,
    image: img('1623341214825-9f4f963727da'),
    rating: 4.9,
    isVeg: false,
    prepTime: 28,
    tags: ['ramen', 'noodles', 'comfort', 'popular'],
    ingredients: ['Ramen noodles', 'Pork broth', 'Chashu', 'Egg', 'Scallion'],
  },
  {
    name: 'Chicken Katsu Curry',
    cuisine: 'Japanese',
    description:
      'Crispy panko chicken cutlet over rice with a mildly sweet Japanese curry sauce.',
    price: 12.5,
    image: img('1604908176997-125f25cc6f3d'),
    rating: 4.6,
    isVeg: false,
    prepTime: 26,
    tags: ['curry', 'fried', 'rice'],
    ingredients: ['Chicken', 'Panko', 'Rice', 'Japanese curry', 'Carrot'],
  },
  {
    name: 'Vegetable Tempura',
    cuisine: 'Japanese',
    description:
      'Assorted seasonal vegetables in a light, crisp tempura batter with tentsuyu dipping sauce.',
    price: 10.0,
    image: img('1581184953963-d15972933db1'),
    rating: 4.4,
    isVeg: true,
    prepTime: 18,
    tags: ['tempura', 'fried', 'vegetarian'],
    ingredients: ['Sweet potato', 'Eggplant', 'Pumpkin', 'Tempura batter', 'Dashi'],
  },
  {
    name: 'Chicken Teriyaki Don',
    cuisine: 'Japanese',
    description:
      'Glazed teriyaki chicken over steamed rice with sesame and spring onion.',
    price: 11.5,
    image: img('1546069901-ba9599a7e63c'),
    rating: 4.5,
    isVeg: false,
    prepTime: 20,
    tags: ['rice bowl', 'glazed', 'comfort'],
    ingredients: ['Chicken', 'Teriyaki', 'Rice', 'Sesame', 'Spring onion'],
  },

  /* ----------------------------- Lebanese ----------------------------- */
  {
    name: 'Chicken Shawarma Wrap',
    cuisine: 'Lebanese',
    description:
      'Spit-roasted spiced chicken wrapped in saj bread with garlic toum, pickles and fries.',
    price: 9.5,
    image: img('1561651823-34feb02250e4'),
    rating: 4.7,
    isVeg: false,
    prepTime: 16,
    tags: ['wrap', 'street food', 'popular'],
    ingredients: ['Chicken', 'Saj bread', 'Toum', 'Pickles', 'Fries'],
    addOns: [
      { name: 'Extra toum', price: 1 },
      { name: 'Hummus side', price: 2.5 },
    ],
  },
  {
    name: 'Falafel Platter',
    cuisine: 'Lebanese',
    description:
      'Crispy herbed chickpea falafel with hummus, tahini, tabbouleh and warm pita.',
    price: 10.0,
    image: img('1593001874117-c99c800e3eb7'),
    rating: 4.6,
    isVeg: true,
    prepTime: 18,
    tags: ['vegan', 'platter', 'healthy'],
    ingredients: ['Chickpeas', 'Parsley', 'Hummus', 'Tahini', 'Pita'],
  },
  {
    name: 'Hummus with Pita',
    cuisine: 'Lebanese',
    description:
      'Silky chickpea hummus drizzled with olive oil and za’atar, served with warm pita triangles.',
    price: 6.5,
    image: img('1577906096429-f73c2c312435'),
    rating: 4.5,
    isVeg: true,
    prepTime: 8,
    tags: ['dip', 'starter', 'vegan'],
    ingredients: ['Chickpeas', 'Tahini', 'Lemon', 'Garlic', 'Olive oil'],
  },
  {
    name: 'Lamb Kofta Skewers',
    cuisine: 'Lebanese',
    description:
      'Char-grilled spiced minced-lamb skewers with grilled tomato, onion and garlic sauce.',
    price: 13.0,
    image: img('1606756790138-261d2b21cd75'),
    rating: 4.6,
    isVeg: false,
    prepTime: 22,
    tags: ['grilled', 'skewers', 'lamb'],
    ingredients: ['Lamb', 'Parsley', 'Onion', 'Spices', 'Garlic sauce'],
  },
  {
    name: 'Tabbouleh Salad',
    cuisine: 'Lebanese',
    description:
      'Fresh parsley and bulgur salad with tomato, mint, lemon and olive oil.',
    price: 7.5,
    image: img('1505253716362-afaea1d3d1af'),
    rating: 4.3,
    isVeg: true,
    prepTime: 12,
    tags: ['salad', 'healthy', 'vegan'],
    ingredients: ['Parsley', 'Bulgur', 'Tomato', 'Mint', 'Lemon'],
  },

  /* ----------------------------- Fast Food ----------------------------- */
  {
    name: 'Classic Cheeseburger',
    cuisine: 'Fast Food',
    description:
      'Juicy beef patty with melted cheddar, lettuce, tomato, pickles and burger sauce in a toasted bun.',
    price: 9.0,
    image: img('1568901346375-23c9450c58cd'),
    rating: 4.7,
    isVeg: false,
    prepTime: 14,
    tags: ['burger', 'beef', 'popular'],
    ingredients: ['Beef patty', 'Cheddar', 'Lettuce', 'Tomato', 'Brioche bun'],
    addOns: [
      { name: 'Bacon', price: 2 },
      { name: 'Extra patty', price: 3 },
    ],
  },
  {
    name: 'Crispy Chicken Burger',
    cuisine: 'Fast Food',
    description:
      'Buttermilk-fried chicken fillet with slaw and spicy mayo in a soft potato bun.',
    price: 9.5,
    image: img('1606755962773-d324e0a13086'),
    rating: 4.6,
    isVeg: false,
    prepTime: 15,
    tags: ['burger', 'fried', 'chicken'],
    ingredients: ['Chicken fillet', 'Slaw', 'Spicy mayo', 'Potato bun', 'Pickles'],
  },
  {
    name: 'Loaded Fries',
    cuisine: 'Fast Food',
    description:
      'Crispy fries topped with melted cheese sauce, jalapeños, crispy onions and chives.',
    price: 6.5,
    image: img('1573080496219-bb080dd4f877'),
    rating: 4.4,
    isVeg: true,
    prepTime: 12,
    tags: ['fries', 'cheese', 'sharing'],
    ingredients: ['Potato', 'Cheese sauce', 'Jalapeño', 'Crispy onion', 'Chives'],
  },
  {
    name: 'Pepperoni Pizza Slice',
    cuisine: 'Fast Food',
    description:
      'Oversized New-York-style slice loaded with pepperoni and stringy mozzarella.',
    price: 5.5,
    image: img('1628840042765-356cda07504e'),
    rating: 4.5,
    isVeg: false,
    prepTime: 10,
    tags: ['pizza', 'cheese', 'quick'],
    ingredients: ['Pizza dough', 'Pepperoni', 'Mozzarella', 'Tomato sauce', 'Oregano'],
  },
  {
    name: 'Crispy Chicken Wings',
    cuisine: 'Fast Food',
    description:
      'Double-fried chicken wings tossed in your choice of buffalo or BBQ glaze, with ranch dip.',
    price: 8.5,
    image: img('1608039755401-742074f0548d'),
    rating: 4.6,
    isVeg: false,
    prepTime: 18,
    tags: ['wings', 'fried', 'sharing'],
    ingredients: ['Chicken wings', 'Buffalo sauce', 'BBQ glaze', 'Ranch', 'Celery'],
  },
];
