/**
 * Additional dishes sourced from TheMealDB (https://www.themealdb.com) — a free,
 * open meal database. Each entry uses a REAL, high-quality photo that matches the
 * dish (the `image` URL is stored in the DB, no binary uploads), keeping the
 * catalogue visually rich across all cuisines. Generated by scripts/genDishes.mjs.
 */
export const extraDishesData = [
  {
    "name": "Spaghetti Bolognese",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Spaghetti Bolognese is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    "rating": 4.7,
    "isVeg": false,
    "prepTime": 30,
    "tags": [
      "italian",
      "noodles"
    ]
  },
  {
    "name": "Spicy Arrabiata Penne",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Spicy Arrabiata Penne is freshly prepared with traditional ingredients and delivered hot.",
    "price": 13.5,
    "image": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
    "rating": 4.6,
    "isVeg": false,
    "prepTime": 25,
    "tags": [
      "italian",
      "spicy"
    ]
  },
  {
    "name": "Vegan Lasagna",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Vegan Lasagna is freshly prepared with traditional ingredients and delivered hot.",
    "price": 16,
    "image": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
    "rating": 4.3,
    "isVeg": true,
    "prepTime": 40,
    "tags": [
      "italian"
    ]
  },
  {
    "name": "Mediterranean Pasta Salad",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Mediterranean Pasta Salad is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14.5,
    "image": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    "rating": 4.4,
    "isVeg": true,
    "prepTime": 30,
    "tags": [
      "italian",
      "noodles"
    ]
  },
  {
    "name": "Potato Gratin with Chicken",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Potato Gratin with Chicken is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15.5,
    "image": "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    "rating": 4.8,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "italian"
    ]
  },
  {
    "name": "Rigatoni with fennel sausage sauce",
    "cuisine": "Italian",
    "description": "An authentic Italian favorite. Rigatoni with fennel sausage sauce is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11,
    "image": "https://www.themealdb.com/images/media/meals/qtqvys1468573168.jpg",
    "rating": 4.9,
    "isVeg": false,
    "prepTime": 15,
    "tags": [
      "italian"
    ]
  },
  {
    "name": "Kung Po Prawns",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. Kung Po Prawns is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9.5,
    "image": "https://www.themealdb.com/images/media/meals/1525873040.jpg",
    "rating": 4.4,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "chinese",
      "seafood"
    ]
  },
  {
    "name": "Ma Po Tofu",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. Ma Po Tofu is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/1525874812.jpg",
    "rating": 4.7,
    "isVeg": true,
    "prepTime": 45,
    "tags": [
      "chinese"
    ]
  },
  {
    "name": "Wontons",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. Wontons is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10,
    "image": "https://www.themealdb.com/images/media/meals/1525876468.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "chinese"
    ]
  },
  {
    "name": "Sweet and Sour Pork",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. Sweet and Sour Pork is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11.5,
    "image": "https://www.themealdb.com/images/media/meals/1529442316.jpg",
    "rating": 4.4,
    "isVeg": false,
    "prepTime": 15,
    "tags": [
      "chinese",
      "dessert"
    ]
  },
  {
    "name": "Szechuan Beef",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. Szechuan Beef is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "chinese"
    ]
  },
  {
    "name": "General Tsos Chicken",
    "cuisine": "Chinese",
    "description": "An authentic Chinese favorite. General Tsos Chicken is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12,
    "image": "https://www.themealdb.com/images/media/meals/1529444113.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "chinese"
    ]
  },
  {
    "name": "Chicken Enchilada Casserole",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Chicken Enchilada Casserole is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "mexican"
    ]
  },
  {
    "name": "Cajun spiced fish tacos",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Cajun spiced fish tacos is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12,
    "image": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "mexican",
      "dessert",
      "seafood"
    ]
  },
  {
    "name": "Braised Beef Chilli",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Braised Beef Chilli is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
    "rating": 4.9,
    "isVeg": false,
    "prepTime": 30,
    "tags": [
      "mexican",
      "spicy"
    ]
  },
  {
    "name": "Crock Pot Chicken Baked Tacos",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Crock Pot Chicken Baked Tacos is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9.5,
    "image": "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
    "rating": 4.8,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "mexican"
    ]
  },
  {
    "name": "Chickpea Fajitas",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Chickpea Fajitas is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg",
    "rating": 4.9,
    "isVeg": true,
    "prepTime": 35,
    "tags": [
      "mexican"
    ]
  },
  {
    "name": "Stuffed Bell Peppers with Quinoa and Black Beans",
    "cuisine": "Mexican",
    "description": "An authentic Mexican favorite. Stuffed Bell Peppers with Quinoa and Black Beans is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10,
    "image": "https://www.themealdb.com/images/media/meals/b66myb1683207208.jpg",
    "rating": 4.3,
    "isVeg": true,
    "prepTime": 40,
    "tags": [
      "mexican",
      "spicy"
    ]
  },
  {
    "name": "Pad See Ew",
    "cuisine": "Thai",
    "description": "An authentic Thai favorite. Pad See Ew is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11.5,
    "image": "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
    "rating": 4.4,
    "isVeg": false,
    "prepTime": 25,
    "tags": [
      "thai"
    ]
  },
  {
    "name": "Thai Green Curry",
    "cuisine": "Thai",
    "description": "An authentic Thai favorite. Thai Green Curry is freshly prepared with traditional ingredients and delivered hot.",
    "price": 13,
    "image": "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
    "rating": 4.7,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "thai",
      "spicy"
    ]
  },
  {
    "name": "Massaman Beef curry",
    "cuisine": "Thai",
    "description": "An authentic Thai favorite. Massaman Beef curry is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12,
    "image": "https://www.themealdb.com/images/media/meals/tvttqv1504640475.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 30,
    "tags": [
      "thai",
      "spicy"
    ]
  },
  {
    "name": "Panang chicken curry (kaeng panang gai)",
    "cuisine": "Thai",
    "description": "An authentic Thai favorite. Panang chicken curry (kaeng panang gai) is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/0dhtwr1763371444.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "thai",
      "spicy"
    ]
  },
  {
    "name": "Drunken noodles (pad kee mao)",
    "cuisine": "Thai",
    "description": "An authentic Thai favorite. Drunken noodles (pad kee mao) is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15,
    "image": "https://www.themealdb.com/images/media/meals/2wx8cm1763373419.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "thai",
      "noodles"
    ]
  },
  {
    "name": "Teriyaki Chicken Casserole",
    "cuisine": "Japanese",
    "description": "An authentic Japanese favorite. Teriyaki Chicken Casserole is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11.5,
    "image": "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    "rating": 4.2,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "japanese"
    ]
  },
  {
    "name": "Honey Teriyaki Salmon",
    "cuisine": "Japanese",
    "description": "An authentic Japanese favorite. Honey Teriyaki Salmon is freshly prepared with traditional ingredients and delivered hot.",
    "price": 17.5,
    "image": "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    "rating": 4.8,
    "isVeg": false,
    "prepTime": 20,
    "tags": [
      "japanese",
      "seafood"
    ]
  },
  {
    "name": "Katsu Chicken curry",
    "cuisine": "Japanese",
    "description": "An authentic Japanese favorite. Katsu Chicken curry is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15.5,
    "image": "https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg",
    "rating": 4.6,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "japanese",
      "spicy"
    ]
  },
  {
    "name": "Chicken Karaage",
    "cuisine": "Japanese",
    "description": "An authentic Japanese favorite. Chicken Karaage is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12,
    "image": "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 25,
    "tags": [
      "japanese"
    ]
  },
  {
    "name": "Yaki Udon",
    "cuisine": "Japanese",
    "description": "An authentic Japanese favorite. Yaki Udon is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15.5,
    "image": "https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg",
    "rating": 4.6,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "japanese"
    ]
  },
  {
    "name": "Lamb tomato and sweet spices",
    "cuisine": "African",
    "description": "An authentic Moroccan favorite. Lamb tomato and sweet spices is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15,
    "image": "https://www.themealdb.com/images/media/meals/qtwtss1468572261.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "african",
      "dessert"
    ]
  },
  {
    "name": "Spicy North African Potato Salad",
    "cuisine": "African",
    "description": "An authentic Moroccan favorite. Spicy North African Potato Salad is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9.5,
    "image": "https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg",
    "rating": 4.8,
    "isVeg": true,
    "prepTime": 15,
    "tags": [
      "african",
      "spicy"
    ]
  },
  {
    "name": "Lamb Tagine",
    "cuisine": "African",
    "description": "An authentic Moroccan favorite. Lamb Tagine is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10,
    "image": "https://www.themealdb.com/images/media/meals/yuwtuu1511295751.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 20,
    "tags": [
      "african"
    ]
  },
  {
    "name": "Chicken Couscous",
    "cuisine": "African",
    "description": "An authentic Moroccan favorite. Chicken Couscous is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10.5,
    "image": "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    "rating": 4.8,
    "isVeg": false,
    "prepTime": 20,
    "tags": [
      "african"
    ]
  },
  {
    "name": "Tahini Lentils",
    "cuisine": "African",
    "description": "An authentic Moroccan favorite. Tahini Lentils is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15,
    "image": "https://www.themealdb.com/images/media/meals/vpxyqt1511464175.jpg",
    "rating": 4.9,
    "isVeg": true,
    "prepTime": 45,
    "tags": [
      "african"
    ]
  },
  {
    "name": "Shakshuka",
    "cuisine": "African",
    "description": "An authentic Egyptian favorite. Shakshuka is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9,
    "image": "https://www.themealdb.com/images/media/meals/g373701551450225.jpg",
    "rating": 4.7,
    "isVeg": false,
    "prepTime": 15,
    "tags": [
      "african"
    ]
  },
  {
    "name": "Garides Saganaki",
    "cuisine": "Continental",
    "description": "An authentic Greek favorite. Garides Saganaki is freshly prepared with traditional ingredients and delivered hot.",
    "price": 13,
    "image": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "continental"
    ]
  },
  {
    "name": "Bakewell tart",
    "cuisine": "Continental",
    "description": "An authentic British favorite. Bakewell tart is freshly prepared with traditional ingredients and delivered hot.",
    "price": 19.5,
    "image": "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
    "rating": 4.4,
    "isVeg": true,
    "prepTime": 45,
    "tags": [
      "continental",
      "dessert"
    ]
  },
  {
    "name": "Apple Frangipan Tart",
    "cuisine": "Continental",
    "description": "An authentic British favorite. Apple Frangipan Tart is freshly prepared with traditional ingredients and delivered hot.",
    "price": 15.5,
    "image": "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
    "rating": 4.4,
    "isVeg": true,
    "prepTime": 30,
    "tags": [
      "continental",
      "dessert"
    ]
  },
  {
    "name": "Smoky Lentil Chili with Squash",
    "cuisine": "Continental",
    "description": "An authentic British favorite. Smoky Lentil Chili with Squash is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12.5,
    "image": "https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg",
    "rating": 4.6,
    "isVeg": true,
    "prepTime": 15,
    "tags": [
      "continental"
    ]
  },
  {
    "name": "Christmas Pudding Flapjack",
    "cuisine": "Continental",
    "description": "An authentic British favorite. Christmas Pudding Flapjack is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12.5,
    "image": "https://www.themealdb.com/images/media/meals/vvusxs1483907034.jpg",
    "rating": 4.6,
    "isVeg": true,
    "prepTime": 45,
    "tags": [
      "continental",
      "dessert"
    ]
  },
  {
    "name": "Eton Mess",
    "cuisine": "Continental",
    "description": "An authentic British favorite. Eton Mess is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
    "rating": 4.9,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "continental"
    ]
  },
  {
    "name": "Lamb Biryani",
    "cuisine": "Indian",
    "description": "An authentic India favorite. Lamb Biryani is freshly prepared with traditional ingredients and delivered hot.",
    "price": 12,
    "image": "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 30,
    "tags": [
      "indian",
      "rice"
    ]
  },
  {
    "name": "Lamb Rogan josh",
    "cuisine": "Indian",
    "description": "An authentic India favorite. Lamb Rogan josh is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10,
    "image": "https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg",
    "rating": 4.5,
    "isVeg": false,
    "prepTime": 20,
    "tags": [
      "indian"
    ]
  },
  {
    "name": "Chicken Handi",
    "cuisine": "Indian",
    "description": "An authentic India favorite. Chicken Handi is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14.5,
    "image": "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    "rating": 4.2,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "indian"
    ]
  },
  {
    "name": "Dal fry",
    "cuisine": "Indian",
    "description": "An authentic India favorite. Dal fry is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9.5,
    "image": "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
    "rating": 4.8,
    "isVeg": true,
    "prepTime": 15,
    "tags": [
      "indian"
    ]
  },
  {
    "name": "Tandoori chicken",
    "cuisine": "Indian",
    "description": "An authentic India favorite. Tandoori chicken is freshly prepared with traditional ingredients and delivered hot.",
    "price": 13,
    "image": "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    "rating": 4.7,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "indian"
    ]
  },
  {
    "name": "Shawarma",
    "cuisine": "Lebanese",
    "description": "An authentic Egyptian favorite. Shawarma is freshly prepared with traditional ingredients and delivered hot.",
    "price": 8,
    "image": "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
    "rating": 4.9,
    "isVeg": false,
    "prepTime": 15,
    "tags": [
      "lebanese"
    ]
  },
  {
    "name": "Falafel",
    "cuisine": "Lebanese",
    "description": "An authentic Turkish favorite. Falafel is freshly prepared with traditional ingredients and delivered hot.",
    "price": 8.5,
    "image": "https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg",
    "rating": 4.8,
    "isVeg": true,
    "prepTime": 15,
    "tags": [
      "lebanese"
    ]
  },
  {
    "name": "Hummus",
    "cuisine": "Lebanese",
    "description": "An authentic Turkish favorite. Hummus is freshly prepared with traditional ingredients and delivered hot.",
    "price": 14,
    "image": "https://www.themealdb.com/images/media/meals/gpon5u1763801180.jpg",
    "rating": 4.3,
    "isVeg": true,
    "prepTime": 45,
    "tags": [
      "lebanese"
    ]
  },
  {
    "name": "kofta burgers",
    "cuisine": "Fast Food",
    "description": "An authentic Turkish favorite. kofta burgers is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11.5,
    "image": "https://www.themealdb.com/images/media/meals/lgmnff1763789847.jpg",
    "rating": 4.4,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "fast food",
      "grilled"
    ]
  },
  {
    "name": "Kentucky Fried Chicken",
    "cuisine": "Fast Food",
    "description": "An authentic United States favorite. Kentucky Fried Chicken is freshly prepared with traditional ingredients and delivered hot.",
    "price": 11,
    "image": "https://www.themealdb.com/images/media/meals/40r49m1763197022.jpg",
    "rating": 4.3,
    "isVeg": false,
    "prepTime": 45,
    "tags": [
      "fast food"
    ]
  },
  {
    "name": "BBQ Pork Sloppy Joes",
    "cuisine": "Fast Food",
    "description": "An authentic United States favorite. BBQ Pork Sloppy Joes is freshly prepared with traditional ingredients and delivered hot.",
    "price": 9.5,
    "image": "https://www.themealdb.com/images/media/meals/atd5sh1583188467.jpg",
    "rating": 4.4,
    "isVeg": false,
    "prepTime": 35,
    "tags": [
      "fast food",
      "grilled"
    ]
  },
  {
    "name": "Chicken Fajita Mac and Cheese",
    "cuisine": "Fast Food",
    "description": "An authentic United States favorite. Chicken Fajita Mac and Cheese is freshly prepared with traditional ingredients and delivered hot.",
    "price": 10.5,
    "image": "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
    "rating": 4.6,
    "isVeg": false,
    "prepTime": 40,
    "tags": [
      "fast food"
    ]
  },
  {
    "name": "Cassava pizza",
    "cuisine": "Fast Food",
    "description": "An authentic Venezuela favorite. Cassava pizza is freshly prepared with traditional ingredients and delivered hot.",
    "price": 8,
    "image": "https://www.themealdb.com/images/media/meals/lrfdwz1764438393.jpg",
    "rating": 4.7,
    "isVeg": false,
    "prepTime": 30,
    "tags": [
      "fast food"
    ]
  }
];
